# Generated by Django 5.0.7 on 2024-08-14 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_categoriematiere_paymentcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='titulaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='student_management_app.professeurs'),
        ),
    ]
