# Generated by Django 5.0.7 on 2024-08-14 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_classes_titulaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
