# Generated by Django 5.0.7 on 2024-08-17 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0004_students_qr_code'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sessionyearmodel',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='periode',
            old_name='nom',
            new_name='periode_name',
        ),
    ]
