# Generated by Django 5.0.7 on 2024-08-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_alter_sessionyearmodel_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matieres',
            name='coefficient',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='statut',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
