# Generated by Django 5.0.7 on 2024-08-18 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_alter_matieres_professeur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matieres',
            name='professeur_id',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres', to='student_management_app.professeurs'),
        ),
    ]
