# Generated by Django 5.0.7 on 2024-08-18 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_alter_matieres_professeur_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='classe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student_management_app.classes'),
        ),
    ]
