# Generated by Django 5.0.7 on 2024-08-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_alter_students_classe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='classe_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='student_management_app.classes'),
        ),
    ]
