# Generated by Django 5.0.7 on 2024-08-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_alter_students_classe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='moyenne_categorie',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rangmatiere',
            unique_together={('eleve', 'matiere', 'periode')},
        ),
    ]
