# Generated by Django 5.0.7 on 2024-08-29 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_note_moyenne_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='categoriematiere',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moyenne',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='moyenneannuelle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='periode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rangmatiere',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Comportement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect', models.CharField(choices=[('retard', 'Retard'), ('absence', 'Absence'), ('participation', 'Participation en classe'), ('qualite_travail', 'Qualité du travail'), ('engagement', 'Engagement'), ('proprete', 'Propreté du matériel'), ('respect_regles', 'Respect des règles')], max_length=20)),
                ('points', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comportements', to='student_management_app.periode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comportements', to='student_management_app.students')),
            ],
        ),
        migrations.CreateModel(
            name='MoyenneCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes', to='student_management_app.categoriematiere')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_categorie', to='student_management_app.students')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyennes_categorie', to='student_management_app.periode')),
            ],
            options={
                'unique_together': {('eleve', 'categorie', 'periode')},
            },
        ),
    ]
