# Generated by Django 5.0.7 on 2024-09-06 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_alter_bulletin_id_alter_categoriematiere_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenBlanc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annee_scolaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_blancs', to='student_management_app.sessionyearmodel')),
                ('classes_concernees', models.ManyToManyField(related_name='examens_blancs', to='student_management_app.classes')),
            ],
        ),
        migrations.CreateModel(
            name='NumeroTableExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_table', models.IntegerField()),
                ('examen_blanc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numero_tables', to='student_management_app.examenblanc')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens_blancs', to='student_management_app.students')),
            ],
            options={
                'ordering': ['numero_table'],
                'unique_together': {('examen_blanc', 'numero_table')},
            },
        ),
    ]
