# Generated by Django 5.0.7 on 2024-09-07 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_cycles_examenblanc_numerotableexamen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(20)])),
                ('rang_matiere', models.IntegerField(blank=True, null=True)),
                ('numero_matiere', models.IntegerField(blank=True, default=1, null=True)),
                ('moyenne_categorie', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examen_notes', to='student_management_app.examenblanc')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examen_notes', to='student_management_app.matieres')),
                ('numero_table_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examen_notes', to='student_management_app.numerotableexamen')),
            ],
        ),
    ]
