# Generated by Django 5.0.7 on 2024-09-07 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_examennote'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoyenneExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rang', models.IntegerField(blank=True, null=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyenne_examen', to='student_management_app.examenblanc')),
                ('numero_table_eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moyenne_examen', to='student_management_app.numerotableexamen')),
            ],
        ),
    ]
