# Generated by Django 5.0.7 on 2024-09-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0015_moyenneexamen'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerotableexamen',
            name='moyenne',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='numerotableexamen',
            name='rang',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
