# Generated by Django 5.0.7 on 2024-09-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0017_alter_customuser_user_type_alter_matieres_categorie_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Econome',
            new_name='Economes',
        ),
    ]
